title: easy-deposit-api
description: >-
  JSON-based deposit service.
baseurl: "/easy-deposit-api"
github_username: DANS-KNAW

# Build settings
markdown: kramdown
theme: jekyll-theme-tactile
plugins:
  - jekyll-feed